FROM python:slim

WORKDIR /bot

COPY requirements.txt .

RUN python3 -m venv .venv
RUN .venv/bin/pip3 install -r requirements.txt

COPY jokes.txt .
COPY jokes.py .
COPY dadbot.py .

CMD [".venv/bin/python", "dadbot.py" ]
